theme: jekyll-theme-tactile
google_analytics: UA-114571919-1
current-contribution-url: "https://github.com/filip-jezek/filip-jezek.github.io/tree/master/_2018-01"
contribution-open: true
contribution-deadline: 23 March
current-newsletter-date: 02 April
url: "https://filip-jezek.github.io"
collections:
  2015-03:
    permalink: /:collection/:path
    title: Old newsletter
    date: 2015-11-04
    output: true
  2018-01:
    permalink: /:collection/:path
    title: First release!
    date: 2018-04-02
    output: true
  2018-00:
    permalink: /:collection/:path
    title: Zero emission
    date: 2018-01-01
    output: true
